### ISSUE TITLE
Microsoft login whitescreen

### ISSUE THREAD

**Issue by JustBohne** [ImNotStealth/MCMicrosoftAuth#1]
![2021-10-11 (1)](https://user-images.githubusercontent.com/91326790/136755387-175384d0-5535-4b8a-867a-b8c38f6dfd64.png)

Hello ImNotStealth can you tell me how to fix this error please.

**Comment by ImNotStealth** [comment]
Any errors? Also it's best if you msg on Discord cos I don't look on github often
